/**
 * Secret word bank. Organized into categories purely so the list stays easy
 * to review and extend — categories are not shown to players and have no
 * effect on gameplay. A flat pool is drawn from at random each round.
 */

export const WORD_CATEGORIES = {
  food: [
    'Pizza',
    'Sushi',
    'Taco',
    'Pancake',
    'Spaghetti',
    'Burrito',
    'Croissant',
    'Dumpling',
    'Waffle',
    'Burger',
    'Ramen',
    'Falafel',
    'Lasagna',
    'Pretzel',
    'Curry',
    'Bagel',
    'Nachos',
    'Sandwich',
    'Popcorn',
    'Ice Cream',
  ],
  animals: [
    'Elephant',
    'Penguin',
    'Octopus',
    'Kangaroo',
    'Giraffe',
    'Dolphin',
    'Hedgehog',
    'Peacock',
    'Cheetah',
    'Platypus',
    'Flamingo',
    'Raccoon',
    'Otter',
    'Chameleon',
    'Koala',
    'Armadillo',
    'Toucan',
    'Walrus',
    'Meerkat',
    'Sloth',
  ],
  places: [
    'Beach',
    'Airport',
    'Library',
    'Museum',
    'Volcano',
    'Castle',
    'Desert',
    'Lighthouse',
    'Jungle',
    'Stadium',
    'Cave',
    'Glacier',
    'Farm',
    'Subway',
    'Waterfall',
    'Campsite',
    'Marketplace',
    'Cruise Ship',
    'Amusement Park',
    'Greenhouse',
  ],
  occupations: [
    'Firefighter',
    'Astronaut',
    'Chef',
    'Dentist',
    'Pilot',
    'Librarian',
    'Electrician',
    'Plumber',
    'Detective',
    'Beekeeper',
    'Referee',
    'Surgeon',
    'Tailor',
    'Photographer',
    'Lifeguard',
    'Zookeeper',
    'Blacksmith',
    'Barista',
    'Architect',
    'Farmer',
  ],
  objects: [
    'Umbrella',
    'Backpack',
    'Telescope',
    'Candle',
    'Mirror',
    'Ladder',
    'Compass',
    'Blender',
    'Typewriter',
    'Flashlight',
    'Suitcase',
    'Hammock',
    'Thermometer',
    'Scissors',
    'Anchor',
    'Trophy',
    'Kettle',
    'Wheelbarrow',
    'Binoculars',
    'Lantern',
  ],
  entertainment: [
    'Circus',
    'Magic Trick',
    'Puppet Show',
    'Karaoke',
    'Board Game',
    'Roller Coaster',
    'Fireworks',
    'Parade',
    'Talent Show',
    'Costume Party',
    'Scavenger Hunt',
    'Puzzle',
    'Video Game',
    'Comic Book',
    'Dance Recital',
    'Film Festival',
    'Escape Room',
    'Carnival',
    'Trivia Night',
    'Concert',
  ],
  nature: [
    'Thunderstorm',
    'Rainbow',
    'Avalanche',
    'Tornado',
    'Sunrise',
    'Eclipse',
    'Blizzard',
    'Earthquake',
    'Tide Pool',
    'Meteor Shower',
    'Wildfire',
    'Fog',
    'Coral Reef',
    'Geyser',
    'Aurora',
    'Sandstorm',
    'Monsoon',
    'Frost',
    'Canyon',
    'Oasis',
  ],
  technology: [
    'Robot',
    'Drone',
    'Satellite',
    'Smartwatch',
    'Printer',
    'Router',
    'Keyboard',
    'Battery',
    'Headphones',
    'Microchip',
    'Webcam',
    'Projector',
    'Solar Panel',
    'Joystick',
    'Speaker',
    'Antenna',
    'Calculator',
    'Camera',
    'Microphone',
    'Charger',
  ],
  sportsAndGames: [
    'Chess',
    'Bowling',
    'Archery',
    'Surfing',
    'Gymnastics',
    'Fencing',
    'Golf',
    'Skateboarding',
    'Rock Climbing',
    'Table Tennis',
    'Rowing',
    'Curling',
    'Snowboarding',
    'Badminton',
    'Wrestling',
    'Darts',
    'Volleyball',
    'Hockey',
    'Cycling',
    'Marathon',
  ],
  holidays: [
    'Birthday Party',
    'Halloween',
    'New Year',
    'Wedding',
    'Graduation',
    'Picnic',
    'Family Reunion',
    'Road Trip',
    'Camping Trip',
    'Sleepover',
    'Bonfire',
    'Potluck',
    'Anniversary',
    'Talent Show',
    'Game Night',
    'Housewarming',
    'Retirement Party',
    'Block Party',
    'Costume Contest',
    'Snow Day',
  ],
} as const;

export type WordCategory = keyof typeof WORD_CATEGORIES;

/** Display label for the Imposter's category hint — see docs/GAME_RULES.md "Imposter privacy". */
const CATEGORY_LABELS: Record<WordCategory, string> = {
  food: 'Food',
  animals: 'Animals',
  places: 'Places',
  occupations: 'Occupations',
  objects: 'Objects',
  entertainment: 'Entertainment',
  nature: 'Nature',
  technology: 'Technology',
  sportsAndGames: 'Sports & Games',
  holidays: 'Holidays & Celebrations',
};

export type WordEntry = {
  word: string;
  category: string;
};

const ALL_WORDS: WordEntry[] = Object.entries(WORD_CATEGORIES).flatMap(([category, words]) =>
  words.map((word) => ({ word, category: CATEGORY_LABELS[category as WordCategory] })),
);

/**
 * Picks a random secret word (with its display category), optionally
 * excluding words already used this session so repeat games stay varied.
 * Falls back to the full pool if every word has been used.
 */
export function getRandomWordEntry(excluding: readonly string[] = []): WordEntry {
  const excludeSet = new Set(excluding);
  const available = ALL_WORDS.filter((entry) => !excludeSet.has(entry.word));
  const pool = available.length > 0 ? available : ALL_WORDS;
  return pool[Math.floor(Math.random() * pool.length)];
}
